# OCCLUSION
OCCL_PATCH_SIZE = 2
OCCL_COLOR = 0
OCCL_SOFTMAX = 0
OCCL_NAME = "occl_" + str(OCCL_PATCH_SIZE) + "_" + str(OCCL_COLOR) + "_" + str(OCCL_SOFTMAX)

# NOISE
NOISE_RADIUS = 3
NOISE_NAME = "noise_" + str(NOISE_RADIUS)

# SARFA
SARFA_RADIUS = 2
SARFA_BLUR = 0
SARFA_NAME = "sarfa_" + str(SARFA_RADIUS) + "_" + str(SARFA_BLUR)

# RISE
RISE_PROBABILITY = 0.5
RISE_MASK_SIZE = 8
RISE_NUM_MASKS = 1000
RISE_SOFTMAX = 0
RISE_NAME = "rise_" + str(RISE_PROBABILITY) + "_" + str(RISE_MASK_SIZE) + "_" + str(RISE_NUM_MASKS) + "_" + str(RISE_SOFTMAX)

# LIME
# SLIC
SLIC_N_SEGMENTS = 200
SLIC_COMPACTNESS = 10
SLIC_SIGMA = 0.25
SLIC_NUM_SAMPLES = 2000
SLIC_NAME = "Lime_slic_" + str(SLIC_N_SEGMENTS) + "_" + str(SLIC_COMPACTNESS) + "_" + str(SLIC_SIGMA) + "_" + str(SLIC_NUM_SAMPLES)

# QUICKSHIFT
QUICKSHIFT_KERNEL_SIZE = 1
QUICKSHIFT_MAX_DIST = 2
QUICKSHIFT_RATIO = 0.0
QUICKSHIFT_NUM_SAMPLES = 1500
QUICKSHIFT_NAME = "Lime_quickshift_" + str(QUICKSHIFT_KERNEL_SIZE) + "_" + str(QUICKSHIFT_MAX_DIST) + "_" \
            + str(QUICKSHIFT_RATIO) + "_" + str(QUICKSHIFT_NUM_SAMPLES)

# FELZENSWALB (scale, sigma, min_size, num_samples)
FELZ_SCALE = 21
FELZ_SIGMA = 0.5
FELZ_MIN_SIZE = 4
FELZ_NUM_SAMPLES = 1000
FELZ_NAME = "Lime_felzenswalb_" + str(FELZ_SCALE) + "_" + str(FELZ_SIGMA) + \
                         "_" + str(FELZ_MIN_SIZE) + "_" + str(FELZ_NUM_SAMPLES)
